import Head from "next/head";
import Header from "components/Header";
import homeStyles from "../styles/home.module.css";
import { sanityClient, urlFor } from "../../sanity";
import { Post } from "typings";
import Link from "next/link";

interface Props {
  posts: [Post];
}

export async function getServerSideProps() {
  const query = `*[_type == 'post'] {
    _id,
    title,
    slug,
    author -> {
      name, 
      image
    },
      description,
      mainImage
 }`;

  const posts = await sanityClient.fetch(query);

  return {
    props: {
      posts,
    },
  };
}

export default function Home({ posts }: Props) {
  console.log(posts);
  return (
    <>
      <Head>
        <title>Taylor&apos;s Medium Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className={homeStyles.landing__banner}>
        <div className={homeStyles.left__banner}>
          <h1>
            {" "}
            <span className="underline__3thick">Medium</span> is a place to
            write, read, and connect
          </h1>
          <h2>
            It&apos;s easy and free to post your thinking on any topic and
            connect with millions of readers.
          </h2>
        </div>

        <img
          src="https://accountabilitylab.org/wp-content/uploads/2020/03/Medium-logo.png"
          alt="Medium Logo"
        />
      </div>

      {/* Posts */}
      <div className={homeStyles.posts__grid}>
        {posts.map((post) => (
          <div key={post._id}>
            <Link key={post._id} href={`/post/${post.slug.current}`}>
              <div className={homeStyles.hover_effect}>
                <img
                  className={homeStyles.post__img}
                  src={urlFor(post.mainImage).url()}
                  alt=""
                />
                <div className={homeStyles.post_descriptors}>
                  <div>
                    <p className={homeStyles.post__title}>{post.title}</p>
                    <p className={homeStyles.post__description}>
                      {post.description} by {post.author.name}
                    </p>
                  </div>
                  <div className={homeStyles.author_img__wrapper}>
                    <img
                      className={homeStyles.author__image}
                      src={urlFor(post.author.image).url()}
                      alt="Picture of myself!"
                    />
                  </div>
                </div>
              </div>
            </Link>
          </div>
        ))}
      </div>
    </>
  );
}
